# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/migrating-from-legacy/

dist: trusty
sudo: false
language: node_js

addons:
  firefox: latest
  chrome: stable

matrix:
  include:
    # Node
    # - node_js: 4
    # - node_js: 5
    # - node_js: 6
    # - node_js: 7
    # - node_js: 8

    # Browsers
    - node_js: 8
      env: KARMA=true

    - node_js: 8
      env: KARMA=true SAUCE=true

  # Don't include SauceLabs tests in the TravisCI status badge, since SauceLabs has its own badge
  fast_finish: true
  allow_failures:
    node_js: 8
    env: KARMA=true SAUCE=true

before_script:
  # Setup a virtual display for browser testing
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  # Always make sure the code passes linting rules
  - npm run lint

  # Build browser distributables before running Karma tests
  - '[[ $KARMA = "true" ]] && npm run build || echo "no build is necessary"'

  # SauceLabs hangs when code coverage is enabled (not sure why), so just run Karma normally.
  # For all other environments, run tests + code coverage.
  - '[[ $SAUCE = "true" ]] && npm run karma || npm run cover'

after_success:
  # concatenate all code-coverage data into a single file
  - ls -R1 coverage/*/lcov.info
  - cat coverage/*/lcov.info > ./coverage/lcov.info

  # send code-coverage data to Codacy
  - cat ./coverage/lcov.info | node_modules/.bin/codacy-coverage -p .

  # send code-coverage data to Coveralls
  - cat ./coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
